use crate::route_gate::{RouteIntent, TaskComplexity};
use crate::types::TaskStatus;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SkillRoute {
    pub name: &'static str,
    pub task_type: &'static str,
    pub primary_intent: &'static str,
    pub recommended_path: &'static str,
    pub status: TaskStatus,
    pub intent: RouteIntent,
    pub complexity: TaskComplexity,
    pub requires_worktree: bool,
    pub branch_prefix: &'static str,
}

const ROUTES: &[SkillRoute] = &[
    SkillRoute {
        name: "dj-grill",
        task_type: "调研对齐",
        primary_intent: "需求澄清",
        recommended_path: "dj-grill → dj-output/dj-implement",
        status: TaskStatus::Planning,
        intent: RouteIntent::Align,
        complexity: TaskComplexity::Complex,
        requires_worktree: false,
        branch_prefix: "feat",
    },
    SkillRoute {
        name: "dj-reason",
        task_type: "调研对齐",
        primary_intent: "需求澄清",
        recommended_path: "dj-grill → dj-output/dj-implement",
        status: TaskStatus::Planning,
        intent: RouteIntent::Align,
        complexity: TaskComplexity::Complex,
        requires_worktree: false,
        branch_prefix: "feat",
    },
    SkillRoute {
        name: "dj-research",
        task_type: "技术调研",
        primary_intent: "技术调研",
        recommended_path: "dj-research",
        status: TaskStatus::Planning,
        intent: RouteIntent::Research,
        complexity: TaskComplexity::Complex,
        requires_worktree: false,
        branch_prefix: "feat",
    },
    SkillRoute {
        name: "dj-output",
        task_type: "写文档",
        primary_intent: "文档产出",
        recommended_path: "dj-output",
        status: TaskStatus::Planning,
        intent: RouteIntent::Document,
        complexity: TaskComplexity::Complex,
        requires_worktree: false,
        branch_prefix: "feat",
    },
    SkillRoute {
        name: "dj-gov",
        task_type: "写文档",
        primary_intent: "文档产出",
        recommended_path: "dj-output",
        status: TaskStatus::Planning,
        intent: RouteIntent::Document,
        complexity: TaskComplexity::Complex,
        requires_worktree: false,
        branch_prefix: "feat",
    },
    SkillRoute {
        name: "dj-implement",
        task_type: "代码开发",
        primary_intent: "继续实现",
        recommended_path: "dj-implement → dj-check",
        status: TaskStatus::InProgress,
        intent: RouteIntent::Implement,
        complexity: TaskComplexity::Complex,
        requires_worktree: true,
        branch_prefix: "feat",
    },
    SkillRoute {
        name: "dj-script",
        task_type: "脚本工具",
        primary_intent: "继续实现脚本或工具",
        recommended_path: "dj-script → dj-check",
        status: TaskStatus::InProgress,
        intent: RouteIntent::Implement,
        complexity: TaskComplexity::Complex,
        requires_worktree: true,
        branch_prefix: "chore",
    },
    SkillRoute {
        name: "dj-tdd",
        task_type: "测试开发",
        primary_intent: "继续 TDD",
        recommended_path: "dj-tdd → dj-check",
        status: TaskStatus::InProgress,
        intent: RouteIntent::Implement,
        complexity: TaskComplexity::Complex,
        requires_worktree: true,
        branch_prefix: "test",
    },
    SkillRoute {
        name: "dj-design",
        task_type: "设计 UI",
        primary_intent: "UI 设计实现",
        recommended_path: "dj-design → dj-implement → dj-check",
        status: TaskStatus::InProgress,
        intent: RouteIntent::Implement,
        complexity: TaskComplexity::Complex,
        requires_worktree: true,
        branch_prefix: "feat",
    },
    SkillRoute {
        name: "dj-hunt",
        task_type: "排查调试",
        primary_intent: "继续排查",
        recommended_path: "dj-hunt → dj-implement → dj-check",
        status: TaskStatus::InProgress,
        intent: RouteIntent::Debug,
        complexity: TaskComplexity::Complex,
        requires_worktree: true,
        branch_prefix: "fix",
    },
    SkillRoute {
        name: "dj-check",
        task_type: "质量检查",
        primary_intent: "质量检查",
        recommended_path: "dj-check",
        status: TaskStatus::InProgress,
        intent: RouteIntent::Check,
        complexity: TaskComplexity::Complex,
        requires_worktree: false,
        branch_prefix: "feat",
    },
    SkillRoute {
        name: "dj-review",
        task_type: "代码审查",
        primary_intent: "代码审查",
        recommended_path: "dj-review",
        status: TaskStatus::InProgress,
        intent: RouteIntent::Check,
        complexity: TaskComplexity::Complex,
        requires_worktree: false,
        branch_prefix: "feat",
    },
    SkillRoute {
        name: "dj-audit",
        task_type: "审计代码",
        primary_intent: "代码审计",
        recommended_path: "dj-audit → dj-implement → dj-check",
        status: TaskStatus::InProgress,
        intent: RouteIntent::Check,
        complexity: TaskComplexity::Complex,
        requires_worktree: false,
        branch_prefix: "feat",
    },
    SkillRoute {
        name: "dj-absorb",
        task_type: "资料吸收",
        primary_intent: "提炼外部材料",
        recommended_path: "dj-absorb → dj-output",
        status: TaskStatus::Planning,
        intent: RouteIntent::Research,
        complexity: TaskComplexity::Complex,
        requires_worktree: false,
        branch_prefix: "feat",
    },
    SkillRoute {
        name: "dj-channel",
        task_type: "协作编排",
        primary_intent: "多 agent 协作",
        recommended_path: "dj-channel",
        status: TaskStatus::InProgress,
        intent: RouteIntent::Implement,
        complexity: TaskComplexity::Complex,
        requires_worktree: false,
        branch_prefix: "feat",
    },
    SkillRoute {
        name: "dj-codebase-design",
        task_type: "代码结构设计",
        primary_intent: "设计模块边界",
        recommended_path: "dj-codebase-design → dj-output",
        status: TaskStatus::Planning,
        intent: RouteIntent::Align,
        complexity: TaskComplexity::Complex,
        requires_worktree: false,
        branch_prefix: "feat",
    },
    SkillRoute {
        name: "dj-dispatch",
        task_type: "需求分类",
        primary_intent: "选择执行路线",
        recommended_path: "dj-dispatch → dj-grill",
        status: TaskStatus::Planning,
        intent: RouteIntent::Align,
        complexity: TaskComplexity::Complex,
        requires_worktree: false,
        branch_prefix: "feat",
    },
    SkillRoute {
        name: "dj-domain-modeling",
        task_type: "领域建模",
        primary_intent: "统一术语",
        recommended_path: "dj-domain-modeling → dj-output",
        status: TaskStatus::Planning,
        intent: RouteIntent::Align,
        complexity: TaskComplexity::Complex,
        requires_worktree: false,
        branch_prefix: "feat",
    },
    SkillRoute {
        name: "dj-git-guardrails",
        task_type: "Git 工作流",
        primary_intent: "检查 Git 护栏",
        recommended_path: "dj-git-guardrails",
        status: TaskStatus::InProgress,
        intent: RouteIntent::Check,
        complexity: TaskComplexity::Complex,
        requires_worktree: false,
        branch_prefix: "feat",
    },
    SkillRoute {
        name: "dj-handoff",
        task_type: "会话交接",
        primary_intent: "保存交接上下文",
        recommended_path: "dj-handoff",
        status: TaskStatus::InProgress,
        intent: RouteIntent::Document,
        complexity: TaskComplexity::Complex,
        requires_worktree: false,
        branch_prefix: "feat",
    },
    SkillRoute {
        name: "dj-meta",
        task_type: "架构自省",
        primary_intent: "理解 DiJiang 架构",
        recommended_path: "dj-meta",
        status: TaskStatus::Planning,
        intent: RouteIntent::Align,
        complexity: TaskComplexity::Complex,
        requires_worktree: false,
        branch_prefix: "feat",
    },
    SkillRoute {
        name: "dj-pattern",
        task_type: "模式研究",
        primary_intent: "识别可复用模式",
        recommended_path: "dj-pattern → dj-output",
        status: TaskStatus::Planning,
        intent: RouteIntent::Research,
        complexity: TaskComplexity::Complex,
        requires_worktree: false,
        branch_prefix: "feat",
    },
    SkillRoute {
        name: "dj-prototype",
        task_type: "原型验证",
        primary_intent: "验证方案可行性",
        recommended_path: "dj-prototype → dj-output",
        status: TaskStatus::InProgress,
        intent: RouteIntent::Implement,
        complexity: TaskComplexity::Complex,
        requires_worktree: true,
        branch_prefix: "feat",
    },
    SkillRoute {
        name: "dj-remix",
        task_type: "站点再造",
        primary_intent: "复刻或重构界面",
        recommended_path: "dj-remix → dj-check",
        status: TaskStatus::InProgress,
        intent: RouteIntent::Implement,
        complexity: TaskComplexity::Complex,
        requires_worktree: true,
        branch_prefix: "feat",
    },
    SkillRoute {
        name: "dj-session-insight",
        task_type: "会话洞察",
        primary_intent: "检索历史会话",
        recommended_path: "dj-session-insight",
        status: TaskStatus::Planning,
        intent: RouteIntent::Research,
        complexity: TaskComplexity::Complex,
        requires_worktree: false,
        branch_prefix: "feat",
    },
    SkillRoute {
        name: "dj-spec-bootstrap",
        task_type: "规范初始化",
        primary_intent: "生成 crate 规范",
        recommended_path: "dj-spec-bootstrap → dj-output",
        status: TaskStatus::Planning,
        intent: RouteIntent::Document,
        complexity: TaskComplexity::Complex,
        requires_worktree: false,
        branch_prefix: "feat",
    },
    SkillRoute {
        name: "dj-split",
        task_type: "任务拆分",
        primary_intent: "拆分可执行任务",
        recommended_path: "dj-split → dj-output",
        status: TaskStatus::Planning,
        intent: RouteIntent::Document,
        complexity: TaskComplexity::Complex,
        requires_worktree: false,
        branch_prefix: "feat",
    },
    SkillRoute {
        name: "dj-write",
        task_type: "文字润色",
        primary_intent: "润色文本",
        recommended_path: "dj-write",
        status: TaskStatus::Planning,
        intent: RouteIntent::Document,
        complexity: TaskComplexity::Complex,
        requires_worktree: false,
        branch_prefix: "feat",
    },
    SkillRoute {
        name: "dijiang-finish-work",
        task_type: "收尾归档",
        primary_intent: "完成工作",
        recommended_path: "dijiang-finish-work",
        status: TaskStatus::Completed,
        intent: RouteIntent::Finish,
        complexity: TaskComplexity::Complex,
        requires_worktree: false,
        branch_prefix: "feat",
    },
    SkillRoute {
        name: "dijiang-continue",
        task_type: "恢复上下文",
        primary_intent: "继续暂停任务",
        recommended_path: "dijiang-continue",
        status: TaskStatus::Paused,
        intent: RouteIntent::Resume,
        complexity: TaskComplexity::Complex,
        requires_worktree: false,
        branch_prefix: "feat",
    },
    SkillRoute {
        name: "dijiang-start",
        task_type: "恢复上下文",
        primary_intent: "重新激活归档任务",
        recommended_path: "dijiang-start",
        status: TaskStatus::Archived,
        intent: RouteIntent::Resume,
        complexity: TaskComplexity::Complex,
        requires_worktree: false,
        branch_prefix: "feat",
    },
];

pub fn skill_route(name: &str) -> Option<&'static SkillRoute> {
    ROUTES.iter().find(|route| route.name == name)
}

pub fn skill_routes() -> &'static [SkillRoute] {
    ROUTES
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn registry_has_unique_skill_names() {
        for (index, route) in ROUTES.iter().enumerate() {
            assert!(ROUTES[..index].iter().all(|other| other.name != route.name));
        }
    }

    #[test]
    fn implementation_routes_define_worktree_metadata() {
        let route = skill_route("dj-hunt").unwrap();
        assert!(route.requires_worktree);
        assert_eq!(route.branch_prefix, "fix");
        assert_eq!(skill_route("dj-check").unwrap().intent, RouteIntent::Check);
    }

    #[test]
    fn registry_covers_routable_skill_names() {
        for skill in [
            "dijiang-continue",
            "dijiang-finish-work",
            "dijiang-start",
            "dj-absorb",
            "dj-audit",
            "dj-channel",
            "dj-check",
            "dj-codebase-design",
            "dj-design",
            "dj-dispatch",
            "dj-domain-modeling",
            "dj-git-guardrails",
            "dj-gov",
            "dj-grill",
            "dj-handoff",
            "dj-hunt",
            "dj-implement",
            "dj-meta",
            "dj-output",
            "dj-pattern",
            "dj-prototype",
            "dj-reason",
            "dj-remix",
            "dj-research",
            "dj-review",
            "dj-script",
            "dj-session-insight",
            "dj-spec-bootstrap",
            "dj-split",
            "dj-tdd",
            "dj-write",
        ] {
            assert!(skill_route(skill).is_some(), "missing route for {skill}");
        }
    }

    #[test]
    fn compatibility_skills_are_not_routable() {
        for skill in ["dj-debt", "dj-health"] {
            assert!(skill_route(skill).is_none(), "{skill} must not own routing");
        }
    }
}
