/// DiJiang session management skills — thin routing layer.
///
/// These are the ONLY skills generated by the DiJiang configurator.
/// They handle session lifecycle (start/continue/finish-work) and route
/// actual work to the existing `dj-*` skill ecosystem:
///
///   dispatch → grill → output → implement/tdd → hunt ↔ check
///
/// The `dj-*` skills are DiJiang's core differentiated assets (17 skills,
/// defined in `~/.pi/agent/skills/dj-*/`). The configurator does NOT
/// duplicate them — it creates thin wrappers that load project context
/// and delegate.

#[rustfmt::skip]
pub mod skill_content {
    /// Wrap markdown content with YAML frontmatter for a DiJiang skill.
    pub fn wrap_frontmatter(name: &str, description: &str, content: &str) -> String {
        format!(
            "---\nname: {}\ndescription: \"{}\"\ntriggers:\n  - session:start\n---\n\n{}",
            name, description, content
        )
    }

    /// Session-init skill: load project context, then delegate to dj-dispatch.
    pub const DIJIANG_START: &str = r#"# Start Session

Initialize a DiJiang-managed development session.

## Step 1: Load Project State

```bash
dijiang status
```

Note: active task path, current phase, git status, developer identity.

## Step 2: Read Workflow

```bash
cat .dijiang/workflow.md
```

DiJiang workflow: **dispatch → grill → output → implement/tdd → hunt ↔ check**

## Step 3: Discover Specs

```bash
ls .dijiang/spec/
cat .dijiang/spec/guides/index.md
```

## Step 4: Delegate to dj-dispatch

This skill only sets up session context. All task classification, routing,
and execution is handled by the `dj-*` skill ecosystem.

Load `dj-dispatch` to classify the user's request and route to the
appropriate `dj-*` skill:

| Request type | Routes to |
|---|---|
| New feature / unclear requirements | `dj-grill` (deep alignment) |
| Feature implementation | `dj-implement` or `dj-tdd` |
| Bug / regression / crash | `dj-hunt` (systematic investigation) |
| Code review / quality check | `dj-check` |
| Documentation / PRD / design | `dj-output` |
| Refactoring / code quality | `dj-ponytail` |
| Prototype / spike | `dj-prototype` |
| Tech debt tracking | `dj-debt` |
| UI design | `dj-design` |
| Script / tooling | `dj-script` |

Ask `dj-dispatch` to classify, then follow its routing.
"#;

    /// Continue session: find active task, resume at correct phase.
    pub const DIJIANG_CONTINUE: &str = r#"# Continue Session

Resume work on the current DiJiang task.

## Steps

1. **Load state**:
   ```bash
   dijiang status
   ```

2. **Find active task and phase** from the output.

3. **Read task artifacts**: `prd.md`, `design.md` (if present), `implement.md` (if present).

4. **Read journal** at `.dijiang/workspace/<developer>/` for context from prior sessions.

5. **Route to the phase-appropriate dj-* skill**:

   | Phase | Skill |
   |---|---|
   | requirements alignment | `dj-grill` |
   | document creation | `dj-output` |
   | implementation | `dj-implement` or `dj-tdd` |
   | investigation / debugging | `dj-hunt` |
   | review / verification | `dj-check` |

   If no active task exists, load `dj-dispatch` to classify the request.
"#;

    /// Finish-work: verify quality, journal, remind commit.
    pub const DIJIANG_FINISH_WORK: &str = r#"# Finish Work

Wrap up the current DiJiang session.

## Steps

1. **Verify quality**: Run `dj-check` if code was written/changed.

2. **Review changes**:
   ```bash
   git diff --stat HEAD
   git status
   ```

3. **Update task status** if needed:
   ```bash
   dijiang task status <name> completed
   ```

4. **Write journal entry** at `.dijiang/workspace/<developer>/`:
   - What was accomplished
   - Key decisions made
   - Remaining work / next steps

5. **Update specs** if learned anything new — use `dj-output` for spec documents.

6. **Remind user** to commit with descriptive message.
"#;

    /// All DiJiang session management skills.
    /// Only 3 skills — the rest is handled by the existing dj-* ecosystem.
    pub fn all_session_skills() -> Vec<(&'static str, &'static str, &'static str)> {
        vec![
            ("dijiang-start",
             "Initialize a DiJiang session: load project context, active task, workflow state, then delegate to dj-dispatch for task routing.",
             DIJIANG_START),
            ("dijiang-continue",
             "Resume work on the current task: find active task and phase, load artifacts, route to the appropriate dj-* skill.",
             DIJIANG_CONTINUE),
            ("dijiang-finish-work",
             "Wrap up the current session: verify quality with dj-check, write journal entry, remind to commit.",
             DIJIANG_FINISH_WORK),
        ]
    }
}
